AllCops:
  NewCops: enable
  Exclude:
    - './test.rb'

# Metrics/LineLength:
#   Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false
